### ISSUE TITLE
support Luarocks

### ISSUE THREAD

**Issue by jtarchie** [jtarchie/heroku-buildpack-openresty#1]
It would be nice to support Luarocks. When push to Heroku it should looks for the package script, and install any of the rocks to a local vendored directory.

**Comment by leafo** [comment]
In case you're interested, I put together my own OpenResty package, but it works a bit differently.

I created the [Lua buildpack](https://github.com/leafo/heroku-buildpack-lua) which comes with LuaRocks. So I've created a rock that has the OpenResty binaries in it: https://github.com/leafo/heroku-openresty

The goal is to not have the Lua based buildpacks re-implement LuaRocks.

**Comment by jtarchie** [comment]
I like it a lot, it allows you to use the a fully supported lua buildpack with the option of openresty. My question would be what compile options are you supporting on the luarock -- postgres, etc? Also, it seems that its hard to control the version of OpenResty that you want to use. I am actually supporting all the versions through the environment variable OPEN_RESTY_VERSION. Any plans for this?

**Comment by jtarchie** [comment]
Actually versioning for OpenResty could be done through git tags. Does your Luarocks support github brach/tags?

**Comment by leafo** [comment]
Yeah, that's a good idea. I had trouble pulling in rocks from Git in the past, but that was about 9 months ago. I'm going to look into it again.
